// <auto-generated />
using System;
using Ironfrost.PlayerService.Services.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ironfrost.PlayerService.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    partial class PlayerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ironfrost.PlayerService.Services.DataBase.Entities.Aett", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("aett_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("emblem_index")
                        .HasColumnType("smallint");

                    b.Property<Guid>("leader_id")
                        .HasColumnType("uuid");

                    b.Property<int>("member_count")
                        .HasColumnType("integer");

                    b.Property<long>("total_points")
                        .HasColumnType("bigint");

                    b.Property<Guid>("world_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("aetts");
                });

            modelBuilder.Entity("Ironfrost.PlayerService.Services.DataBase.Entities.Player", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("aett_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("emblem_index")
                        .HasColumnType("smallint");

                    b.Property<long>("total_points")
                        .HasColumnType("bigint");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("village_count")
                        .HasColumnType("integer");

                    b.Property<Guid?>("world_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("players");
                });
#pragma warning restore 612, 618
        }
    }
}
