services:
  authentication:
    build:
      context: ./Ironfrost.Authentication
    ports:
      - "5288:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnection__Host=${DB_HOST}
      - DbConnection__Port=${DB_PORT}
      - DbConnection__Username=${DB_USERNAME}
      - DbConnection__Password=${DB_PASSWORD}
      - DbConnection__Database=${AUTH_DB_NAME}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}

  game-service:
    build:
      context: ./Ironfrost.GameService
    ports:
      - "5224:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnection__Host=${DB_HOST}
      - DbConnection__Port=${DB_PORT}
      - DbConnection__Username=${DB_USERNAME}
      - DbConnection__Password=${DB_PASSWORD}
      - DbConnection__Database=${GAME_DB_NAME}

  player-service:
    build:
      context: ./Ironfrost.PlayerService
    ports:
      - "5236:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnection__Host=${DB_HOST}
      - DbConnection__Port=${DB_PORT}
      - DbConnection__Username=${DB_USERNAME}
      - DbConnection__Password=${DB_PASSWORD}
      - DbConnection__Database=${PLAYER_DB_NAME}
