// <auto-generated />
using System;
using Icefrost.GameService.Services.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Icefrost.GameService.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Icefrost.GameService.Services.DataBase.Entities.Village", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("loyalty")
                        .HasColumnType("smallint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("owner_id")
                        .HasColumnType("uuid");

                    b.Property<long>("points")
                        .HasColumnType("bigint");

                    b.Property<Guid>("world_id")
                        .HasColumnType("uuid");

                    b.Property<short>("x")
                        .HasColumnType("smallint");

                    b.Property<short>("y")
                        .HasColumnType("smallint");

                    b.HasKey("id");

                    b.ToTable("villages");
                });

            modelBuilder.Entity("Icefrost.GameService.Services.DataBase.Entities.VillageBuilding", b =>
                {
                    b.Property<Guid>("village_id")
                        .HasColumnType("uuid");

                    b.Property<byte>("building_type")
                        .HasColumnType("smallint");

                    b.Property<bool>("is_upgrading")
                        .HasColumnType("boolean");

                    b.Property<byte>("level")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("upgrade_finish_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("village_id", "building_type");

                    b.ToTable("village_buildings");
                });

            modelBuilder.Entity("Icefrost.GameService.Services.DataBase.Entities.VillageTroop", b =>
                {
                    b.Property<Guid>("village_id")
                        .HasColumnType("uuid");

                    b.Property<byte>("troop_type")
                        .HasColumnType("smallint");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.HasKey("village_id", "troop_type");

                    b.ToTable("village_troops");
                });

            modelBuilder.Entity("Icefrost.GameService.Services.DataBase.Entities.World", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("bot_count")
                        .HasColumnType("integer");

                    b.Property<int>("capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("server_type")
                        .HasColumnType("smallint");

                    b.Property<float>("speed_modifier")
                        .HasColumnType("real");

                    b.Property<int>("wild_villages")
                        .HasColumnType("integer");

                    b.Property<byte>("win_condition")
                        .HasColumnType("smallint");

                    b.HasKey("id");

                    b.ToTable("worlds");
                });
#pragma warning restore 612, 618
        }
    }
}
