@Authentication_HostAddress = http://localhost:5288
@jwt_admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGFuYWFhQGFkbWluLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwianRpIjoiYzMwMWZlOWMtYmI5MS00MzA0LThjZmEtYTk2ZWFmZTRhMjI3IiwiZXhwIjoxNzc1NzM5Mjg0LCJpc3MiOiJBdXRoZW50aWNhdGlvbklzc3VlciJ9.zCCW-YN-HEjnUPg6RdpsqiURQwJj55l3_0c9EQjq3Sw

POST http://localhost:5288/api/Authentication/Login
Content-Type: application/json

{
  "username": "AlanFS",
  "password": "Alan123.FFF",
  "email": "alanfs10@gmail.com",
  "isAdmin": false
}

###

POST http://localhost:5288/api/Authentication/Login
Content-Type: application/json

{
  "username": "alanaaa",
  "email": "alanaaa@admin.com",
  "password": "fcgAdmin123."
}

###

POST http://localhost:5288/api/Authentication/CreateAccount
Content-Type: application/json

{
  "username": "alanaaa",
  "email": "alanaaa@admin.com",
  "password": "fcgAdmin123.",
  "isAdmin": true
}

###

POST http://localhost:5288/api/UserCreator/CreateUser
Content-Type: application/json
Authorization: Bearer {{jwt_admin}}

{
  "username": "AlanFS",
  "password": "Alan123.FFF",
  "email": "alanfs10@gmail.com",
  "isAdmin": false
}

###

POST http://localhost:5288/api/UserCreator/CreateUser
Content-Type: application/json
Authorization: Bearer {{jwt_admin}}

{
  "username": "Alanfsaa",
  "password": "Alan123.aaa",
  "email": "alanfs101aaaaa@gmail.com",
  "isAdmin": false
}

###

