// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Icefrost.Authentication.Services;

#nullable disable

namespace Icefrost.Authentication.Migrations
{
    [DbContext(typeof(PostgreDb))]
    [Migration("20251104134242_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Authentication.Services.Entities.GameRegistry", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("base_price")
                        .HasColumnType("numeric");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("registry_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("game_registry");
                });

            modelBuilder.Entity("Authentication.Services.Entities.UserGames", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("game_ids")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("user_id");

                    b.ToTable("user_games");
                });

            modelBuilder.Entity("Authentication.Services.Entities.Users", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_admin")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Authentication.Services.Entities.UserGames", b =>
                {
                    b.HasOne("Authentication.Services.Entities.Users", "users")
                        .WithOne("userGames")
                        .HasForeignKey("Authentication.Services.Entities.UserGames", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("Authentication.Services.Entities.Users", b =>
                {
                    b.Navigation("userGames");
                });
#pragma warning restore 612, 618
        }
    }
}
